enoren5/tarot_juicer

scripts/.gitignore
scripts/inject_sqlite.py

Fixing bug, where I was missing the field before trying to inject data.

Fix bug in inject_sql script to insert missing column to generators_generator

---

generators/views.py
staticfiles/css/style.css
templates/landings/portal.html

…p for none, and social icon color

Forth Work Order

---

scripts/injector/injector.py

Try these changes to correct the gateway and admin dashboard bugs
1) YourMagicPassphrase was not working (bug)
2) admin user and password for the dashboard were removed (bug)

Slipsnip automation fix dashboard login and passphrase

---

generators/views.py

This should fix the card order problem, let me know.

fix card order bug issue 31

---

.gitignore
tarot_juicer/static/css/gateway.css
templates/landings/gateway.html

> I have modified the CSS for the body tag, removed its margin causing the alert div to move a little bit to left, added animation instead of writing javascript ( because why we write javascript code if we can achieve the same with CSS ) code.
That's all, I had done, thank you @enoren5 
Best Regards,
Umar Ahmed

Css js corrections

---

accounts/models.py
accounts/urls.py
accounts/views.py
essays/urls.py
essays/views.py
generators/urls.py
generators/views.py
landings/urls.py
landings/views.py
tarot_juicer/middlewares.py
templates/base.html
templates/generators/tarot_key.html
templates/landings/portal.html
templates/partials/_navbar.html

> Instead of creating a fake user from setting.py ( which is hardcoded ) and we need a dynamic mechanism to create users with a random name and password. So, I created some methods that create a random user, If it does not exist in the current session of the browser. 
> Changed the URL pattern for accessing the portal. 
> Updated views.py to check for the user in the current session and also updated the Auth toggle functionality to kick all users at once.
> Lastly updated middleware redirections.
That's all, I had done, thank you @enoren5  
Best Regards,
Umar Ahmed

Created a mechanism for dynamic user handling

---

tarot_juicer/settings.py

Hey @enoren5
I have make a condition, like in heroku it will search for `DATABASE_URL` as an environmental variable or config vars in heroku. If `DATABASE_URL` is not defined in local machine then it will fallback to use default `sqlite` DB, On the other hand, if it is on heroku and `DATABASE_URL` is defined with a postgre's database url, then it will set it to postgre with max age and SSL.
That's all, I had done brother.
Best Regards,
Umar Ahmed

Update database configuration

---

tarot_juicer/settings.py

- First it checks for `DB_HEROKU_POSTGRES` variable which is Heroku PostgreSQL db locally, If it is not found,
- It checks for `db.sqlite3` ,If it is not exists,
- It checks for `DB_HEROKU` variable which is Heroku db AWS remotely.
> It is working exactly same as the video of a person you shared with me.
Thank you, Best Regards
Umar Ahmed :+1:

heroku locally and remotely

---

tarot_juicer/settings.py

Updated automation of swapping DBs

Updated automation of swapping DBs

---

accounts/views.py
tarot_juicer/settings.py

Updated Secure
> updated check deploy variables
> updated attempts reset on logout
@enoren5 :heart: Thank you :rocket:

Updated Secure

---

tarot_juicer/settings.py
templates/generators/tarot_key.html

There was only a mistake of a single ` ' ` comma and also updated code.

Card at random

---

essays/urls.py

> So In our case, I had simply put `article/<str:web_address>/` path to the bottom of urlpattern's array, So django first check for all the views defined then in last it will check for this path `article/<str:web_address>/`. That means the higher prioity will be given to the views defined.
That's all I had @enoren5 brother

(template) routing incorrectly

---

generators/views.py
tarot_juicer/static/css/tarot_key.css
templates/generators/tarot_key.html

@enoren5 that's all i had done.
Best Regards,
Umar Ahmed

Implement left and right buttons

---

tarot_juicer/settings.py

Django Secure

---

essays/models.py
tarot_juicer/static/css/essay-main.css
templates/essays/watchtower.html

Updated biblio

---

tarot_juicer/urls.py
tarot_juicer/views.py
templates/404.html
templates/500.html

Added 404 and 500 error pages
By overriding default views of pages to our own custom views !
that's all I had @enoren5

Added error pages

---

accounts/models.py
accounts/views.py
tarot_juicer/middlewares.py
templates/landings/gateway.html

Enhanced Auth Toggle

---

templates/base.html
templates/landings/gateway.html
templates/landings/portal.html

Hey @enoren5, please merge the branch, to add google analytics on the site.
that's all, I had done !

Issue 123 Analytics

---

tarot_juicer/middlewares.py
tarot_juicer/notification.py
tarot_juicer/views.py

Updated the admin banner to show on login page as well as logged in page

Update Banner Issue

---

tarot_juicer/middlewares.py
tarot_juicer/notification.py
tarot_juicer/static/css/portal.css
tarot_juicer/static/css/style.css
tarot_juicer/views.py
templates/base.html
templates/landings/portal.html
templates/partials/_alerts.html

Added Admin Access Banner On All Pages

Issue #122

---

tarot_juicer/middlewares.py
tarot_juicer/notification.py
tarot_juicer/views.py

Updated banner issue

---

tarot_juicer/settings.py

Changed the named of config var from `DJANGO_DEBUG` to  `DEBUG` for better code readability

Update DEBUG config variable

---

tarot_juicer/static/js/tarot_key.js

> I had made the st Paul default selection(you need to clear your cache to view the functionality) and also when ever the visitor view any page then the selection is saved in `localStorage`
> Also I added comments, you can check it out and send you a video
Thank you @enoren5 brother ❤️

Make St Paul Default

---

tarot_juicer/static/js/tarot_key.js
templates/generators/tarot_key.html

> Comment out Regular/Study, both javascript and html functions
that's all I had done @enoren5 brother

Update Tarot Key

---

tarot_juicer/static/js/tarot_key.js
templates/generators/tarot_key.html

> Brother, now I tested the issue properly and fixed it.
Thank you

Updated the issue

---

tarot_juicer/settings.py
templates/base.html

Feature Update
